name: Camp
version: '${version}'

main: cn.plumc.camp.Camp
api-version: '1.18'
load: POSTWORLD

authors: [ PlumeIS ]

commands:
  camp:
    description: Main command of Camp
    usage: /<command> [create/disband/list/auth/modify/member]
    permissions: camp

permissions:
  camp:
    default: true
  camp.create:
    default: true
  camp.disband:
    default: true
  camp.list:
    default: true
  camp.list.camp:
    default: true
  camp.auth.rankup:
    default: true
  camp.auth.rankdown:
    default: true