name: Camp
version: '${version}'

main: cn.plumc.camp.Camp
api-version: '1.18'
load: POSTWORLD

authors: [ PlumeIS ]

commands:
  usage: ABABAB
  permissions:
    camp.create: default
    camp.disband: default